POST http://localhost:4000/app/signup
Content-Type: application/json

{
    "firstName": "Christian",
    "lastName": "Joseph",
    "email": "sep@yahoo.com",
    "occupation": "Developer",
    "city": "Berlin",
    "password": "josjos"
}