POST   http://localhost:4000/app/signup
Content-Type: application/json

{
    "firstName": "Junior",
    "lastName": "Shelley",
    "email": "shelley@gmail.com",
    "occpation": "Teacher",
    "city": "Belfast",
    "password": "09878",
    "date": "09.08.2021"
}